name: Deploy to Development

on:
  push:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Check for outdated dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list --outdated || true  # Don't fail if no outdated packages
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        startup-command: 'bash startup.sh'
        
    - name: Run post-deployment tests
      run: |
        sleep 60  # Wait longer for app to start and install dependencies
        curl -f https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net/health || exit 1